### ISSUE TITLE
some oversized app cannot be cloned in android Q

### ISSUE THREAD

**Issue by nx111** [PeterCxy/Shelter#103]
Some oversized app (eg. com.tencent.mm, 150M+) cannot be cloned in my galaxy s10+(android Q).  When I select the oversized app and begin cloning, nothing happend,  the cloneable apps will not be cloned any more. I have to wait some time for the thread end, then the cloneable apps can be clone again.

**Comment by nx111** [comment]
after write some date to outputstream, flush it will fix this issue.

here is my patch: [https://github.com/nx111/Shelter/commit/61fcfa36441865c0c821ee61f121161312eb0e34](https://github.com/nx111/Shelter/commit/61fcfa36441865c0c821ee61f121161312eb0e34)

**Comment by nx111** [comment]
someting is wrong in Q still.

**Comment by nx111** [comment]
In Q, clone app or install apk maybe need more work.

**Comment by nx111** [comment]
fixed : [pull 104](https://github.com/PeterCxy/Shelter/pull/104)

**Comment by Matvei27** [comment]
I compiled from your repository but still could not clone com.tencent.mm
