### ISSUE TITLE
Motorola X Play Dual Sim - Android 7.1.1 - App Drawer empty

### ISSUE THREAD

**Issue by jPPuetz** [PeterCxy/Shelter#109]
Hi,

after installating Shelter everything work fine for some minutes/hours. But after I reboot the phone or after a random crash of the App "Google" the App Drawer is empty/gone untill I uninstall Shelter (remove the work profile) again.

Here some information from the bug report in Android about my phone:
`Build: NPD26.48-24-1
Build fingerprint: 'motorola/lux_retasia_ds/lux_uds:7.1.1/NPD26.48-24-1/1:user/release-keys'
Bootloader: 0x80F3
Radio: M8936_20250112.18.05.38R LUX_EMEA_DSDS_CUST
Kernel: Linux version 3.10.49-gd043ad1-00008-gbcf239c (hudsoncm@ilclbld35) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon Sep 11 02:09:44 CDT 2017
Command line: boot_cpus=0,1,4,5,6,7 sched_enable_hmp=1 console=null androidboot.hardware=qcom msm_rtb.filter=0x3F ehci-hcd.park=3 vmalloc=400M androidboot.bootdevice=7824900.sdhci movablecore=160M buildvariant=user androidboot.emmc=true androidboot.serialno=********** androidboot.baseband=msm androidboot.mode=normal androidboot.device=lux androidboot.hwrev=0x82C0 androidboot.radio=0x4 androidboot.powerup_reason=0x00004000 androidboot.bootreason=reboot androidboot.write_protect=1 msm_poweroff.download_mode=0 androidboot.fsg-id= androidboot.secure_hardware=1 androidboot.cid=0x7 androidboot.wifimacaddr=******** androidboot.btmacaddr=**************** mdss_mdp.panel=1:dsi:0:qcom,mdss_dsi_mot_tdi_546_1080p_cmd_v1 androidboot.bootloader=0x80F3 androidboot.carrier=retfr androidboot.hardware.sku=XT1562 androidboot.bl_state=1
Bugreport format version: 1.0
Dumpstate info: id=1 pid=20824`

Here a screenshot of the issue:
![screenshot-2020-01-26-08-57-06-1](https://user-images.githubusercontent.com/12053785/73132470-04ae1180-401c-11ea-9b14-1f47ad104bac.png)

Should I attach or can I send someone the full bug report? Or should I create a logcat log?

**Comment by PeterCxy** [comment]
These bugs have nothing to do with Shelter. Please contact your phone manufacturer for general work profile issues.
