### ISSUE TITLE
support of custom launchers

### ISSUE THREAD

**Issue by br4nnigan** [PeterCxy/Shelter#115]
The default launcher on LOS16, Trebuchet, has a "work" tab in the app drawer but with Evie Launcher there is no such option in the interface. I have to switch to Trebuchet every time I want to start a sheltered app.

What do?

**Comment by auz-jsm** [comment]
The developer of the said launcher that can't display work profile apps should you be addressing to. They're the one that will implement their launcher to support work profile apps.

Just like Microsoft Launcher they add a support for work profile apps.
