### ISSUE TITLE
[Announcement] Status of the Project (Spoiler: Not Dead)

### ISSUE THREAD

**Issue by PeterCxy** [PeterCxy/Shelter#120]
I know I haven't checked on this project for quite a while. I am a final year student in university right now and really need to get my things done. I know I have been active on some of my other projects, but my spare time for now really does not allow for too many simultaneous projects.

If things go as expected, I should graduate in this June, from when I will have a gap year but need to get my English language exams done in order to apply for Master programs in North America. I will try to get back to this project as soon as possible. Android 11 compatibility will be handled once AOSP releases source code of the final release version of Android 11.

This project will NOT get abandoned any time soon because it's one of my must-use applications on my daily driver phone. It will continue soon.

**Comment by letkan** [comment]
Just noticed this, glad you didn't abandon this project.

**Comment by Tyler-2** [comment]
This is great and I just discovered Shelter and the work profile features of Android.

**Comment by auz-jsm** [comment]
I'll religiously waiting for this since my phone is now Android 11.
_(the one submitted before the issue #110)_

**Comment by PeterCxy** [comment]
@auz-jsm I have been running Shelter on Android 11 for months. You are replying to a post made over a year ago.
