### ISSUE TITLE
Shelter doesn't recognize the Work Profile created by itself after upgrading Magisk

### ISSUE THREAD

**Issue by outloudvi** [PeterCxy/Shelter#125]
Shelter version: 1.5
Magisk: Upgrade from 20.3 to 20.4
ROM: LineageOS 16

After my upgrading Magisk from 20.3 to 20.4, Shelter doesn't recognize the Work Profile created by itself, and asks to create a new one.

**Comment by PeterCxy** [comment]
The only possible reason Shelter may "forget" its own Work Profile is when its data is somehow destroyed. The state of Shelter is stored in its data directory in /data, so maybe Magisk broke something there?

**Comment by outloudvi** [comment]
Uninstalled Magisk, installed Magisk 20.3, enabled Magisk hide, uninstalled and reinstalled Shelter and upgraded Magisk 20.4 (not installing any modules). Seems not a problem between Magisk and Shelter. Maybe the issue can be closed unless anyone got further idras.

**Comment by outloudvi** [comment]
@PeterCxy This problem reproduces moments before. I only installed an App, backed it up with Titanium Backup, and disabled it with MyAndroidTools. So maybe this problem is not related to Magisk.

Could you expand on the destroyed data? Maybe I can record the data before and after (potentially) the next reproduction and compare them. If I hope to do this, what should I archive for now? I only see `shared_prefs/net.typeblog.shelter_preferences.xml` and  `shared_prefs/prefs.xml` under `/data/data/net.typeblog.shelter` after setting up Shelter again, is there anywhere else I need to seek?

**Comment by PeterCxy** [comment]
@outloudvi it's just the prefs.xml. If that file is cleared, then Shelter will not recognize any work profile.

**Comment by outloudvi** [comment]
Thanks. I've archived it. I'll come back when it reproduces a third time.
