### ISSUE TITLE
FileShuttleService.createFile() should handle null mimeType

### ISSUE THREAD

**Issue by zhanghai** [PeterCxy/Shelter#132]
Although there is no documentation about whether the `mimeType` parameter is nullable or non-null in [`DocumentsProvider.createDocument`](https://developer.android.com/reference/android/provider/DocumentsProvider#createDocument(java.lang.String,%20java.lang.String,%20java.lang.String)), framework `ExternalStorageProvider` handles a `null` mime type correctly. This is also useful for file managers because it needs to copy files without any known mime type, while preserving the name.

`ExternalStorageProvider` currently inherits from `FileSystemProvider`, which calls `FileUtils.buildUniqueFile()` and then `FileUtils.splitFileName()`. It correctly handles no extension from mime type on [FileUtils.java#1195](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/FileUtils.java;l=1195;drc=bc3d8b9071d4f0b2903d6836770d974e70366290). However in `FileShuttleService.createFile()`, a null extension results in appending `.null` to the file name on [FileShuttleService.java#133](https://github.com/PeterCxy/Shelter/blob/d4371f6a837b3b4487ca49225a609b1704e79ba5/app/src/main/java/net/typeblog/shelter/services/FileShuttleService.java#L133), which is undesirable.

I learned about this issue at zhanghai/MaterialFiles#225.

I could have sent a PR about this, but I'm forbidden by my employer from doing so because they don't categorize WTFPL as a valid open source license. So could you take a look at this issue?

**Comment by PeterCxy** [comment]
I will fix this once I have more spare time after graduation (see #120) along with Android 11 support for File Shuttle.
