### ISSUE TITLE
Preventing accidental softbrick with instructions to README and Specification

### ISSUE THREAD

**Issue by matu3ba** [PeterCxy/Shelter#138]
1. Setup process does not finish
2. Copying apps into the shelter does not work
3. After the copy operation the app can not be removed anymore and probably can not be updated.

Very sad to see no working and reliable open source privacy sandboxing solution.

**Comment by linsui** [comment]
May [this](https://github.com/PeterCxy/Shelter/issues/129) can help you?

**Comment by matu3ba** [comment]
@linsui Yes, indeed. Thanks alot. Would be great to mention the needed instructions and a link to what kind of privacy things are restricted and not restricted with user profiles.
Will file a PR to address the missing procedure until Thursday.

**Findings**
1. Installing the .apk file of aurora store with the menu worked.
2. Copying is broken. You may want to remove that or hint that it is broken (I guess due to missing root access to access to /data/data/..)
3. Restart is needed for Android to cache the installed apps (from aurora store)

**File system restriction**
Is there any way to restrict more granular filesystem access to certain paths, because any app could theoretically copy all files (ie as thumbnails)? Do you know any working solution for that?
On Linux desktop there is **firejail**, but it has a **big attack surface**.

**Comment by linsui** [comment]
These problems will [be fixed soon](https://github.com/PeterCxy/Shelter/issues/110) and the workaround has been pinned in issues. So I'll just wait. 😄

**Comment by matu3ba** [comment]
@linsui Whatsapp can not be removed after installation. This is extremely weird. :-1:
