### ISSUE TITLE
Can't set up device: "Permission is denied or Unsupported device

### ISSUE THREAD

**Issue by jwmh** [PeterCxy/Shelter#140]
Unable to setup Shelter: unsupported device (stock ROM, NO root)

Yes, I've thoroughly read all the READMEs, issues, etc.
I have successfully set it up on a *different* device running Android 7.x

But on this device (which is my only device right now), it fails:
Hot Pepper Poblano VL5
OS: Android Go
Android 8.1.0

Stock firmware and all,  never rooted.
I click Continue at the initial setup screen, and...
"
Can't set up device
Contact your admin for help
"
"Permission is denied or Unsupported device.
"
.
I:
- manually changed every permission and notification setting I could find,
 incl. 
-- turning it on as Device Administrator, etc.
- turned off "draw over other apps" apps (Tap'n'Turn, RedMoon).
- turned off Do Not Disturb
- etc.
.
Force stopped Shelter and tried again...
... Still failing Setup.
.
Hints??
Maybe my device doesnt have a Work Profile mode support???
(Android Go)
.
Edit/p.s.
I mean, obviously it is unsupported.
But my question is...
... Why?
What's going on under the hood,  that makes this not work?

**Comment by PeterCxy** [comment]
Work Profiles are simply not supported on Android Go.
