### ISSUE TITLE
Install apps from unknown sources.

### ISSUE THREAD

**Issue by knakworstsalade** [PeterCxy/Shelter#141]
So I needed to install an app from an unknown source.
I got the pop up to enable it which I did. Now I want to disable it and not leave it open but I can't figure out how to do it.
If I try to clone settings into shelter it doesn't work.

I am using an s10+ with Android 10.

**Comment by Lvl4Sword** [comment]
If you search for "Install unknown apps" within settings, that should take you to the screen that'll show you all of the programs you've allowed/disallowed.
Let me know if that helps.
