### ISSUE TITLE
[Feature] Dual Sim support

### ISSUE THREAD

**Issue by Caaruzo** [PeterCxy/Shelter#145]
Greetings,

I installed your App on my phone, and really love it to separate work-apps from private ones. First of all, thanks for that.
I was just missing one feature, so I hope you could implement this in future.

I cloned my phone and contacts app (Samsung smartphone) into shelter. Everything works fine and is separated. Separate Google ACC, separate contacts, great. But I really would love to have an option, to choose which sim-card is getting used for shelter contacts on call. Do you think that’s possible? Would really love to see that.

Thanks very much.
Greetings Caaruzo

**Comment by PeterCxy** [comment]
There is no Android API for that. I'm sorry but Shelter cannot implement something that's just not supported by Android at all.

**Comment by Caaruzo** [comment]
why not making use of "Call Relay?" People already done this in that way, just not for an shellter. So you could check via shellter, if phone number is found in Shellter contect book, then use card 2. if its in the other one use card 1. if its nowhere, use defalt or ask which to use.
