### ISSUE TITLE
ugly shortuct icon

### ISSUE THREAD

**Issue by 532910** [PeterCxy/Shelter#148]
Shelter's shortcut icon looks ugly:
![image](https://user-images.githubusercontent.com/14617699/87489625-2ba0e400-c64c-11ea-9857-2f760716bf97.png)
![image](https://user-images.githubusercontent.com/14617699/87489651-36f40f80-c64c-11ea-95a9-cd1f480f246e.png)

**Comment by PeterCxy** [comment]
Unfortunately I can't do anything about this. Shelter can only create shortcut icons, never real app icons, which has serious limitations, especially on the adaptive icon side.

**Comment by 532910** [comment]
I believe you're wrong, for example [transistor](https://github.com/y20k/transistor) and firefox (preview/nightly) creates nice shortcuts:
![image](https://user-images.githubusercontent.com/14617699/87670331-39538800-c778-11ea-8fd2-ed7ca3a785a2.png)

**Comment by PeterCxy** [comment]
If those icons were owned by Shelter, then yes, Shelter can do those nice icons. But when those icons are from other applications, then the only thing Shelter can do is to render them as a Bitmap and then use that as the icon, losing all the adaptive metadata, and it is then up to the OS to decide how to paint those icons.

**Comment by 532910** [comment]
Could you check
https://github.com/y20k/transistor/issues/210
https://source.android.com/devices/tech/display/adaptive-icons#known-issues
for details.

**Comment by PeterCxy** [comment]
Those are of no help to the problem Shelter faces.

**Comment by 532910** [comment]
What is wrong to show working profile icon:
![image](https://user-images.githubusercontent.com/14617699/87670963-41f88e00-c779-11ea-9da2-e62a6c8b6688.png)
Google images search show a lot nice icons:
https://www.androidpolice.com/wp-content/themes/ap2/ap_resize/ap_resize.php?src=https%3A%2F%2Fwww.androidpolice.com%2Fwp-content%2Fuploads%2F2018%2F05%2Fandroid-p-enterprise.png&w=728
https://docs.samsungknox.com/dev/knox-sdk/existing-android-profiles.htm

**Comment by PeterCxy** [comment]
If you mean the icon at the right-bottom corner, it is not controlled by Shelter and instead controlled by your launcher. An shortcut created by Shelter cannot use an icon other than Shelter's own icon at that position.

Pictures linked by you are all default icons shown by the Android launcher for work profile applications. If you don't use Shelter's "freeze" feature, then you don't need to use Shelter's shortcuts anyway. If you need to use Shelter's "freeze" feature, then there is no way to keep the original icon for work profile apps.

Also, the GitHub issue list is now deprecated. Further discussions should go to the new mailing list.

**Comment by 532910** [comment]
sr.ht doesn't allow me to register my username.

**Comment by PeterCxy** [comment]
You do NOT need to register in order to take part in the mailing list. Just click subscribe or create new post in the page for the mailing list.

**Comment by 532910** [comment]
What is the reason to create shelter's shortcut?
![image](https://user-images.githubusercontent.com/14617699/87861763-e3d2d300-c951-11ea-892a-5d09ed7610b5.png)
Is it possible to create the leftmost icon from shelter?

> the only thing Shelter can do is to render them as a Bitmap

Moreover, I believe Shelter renders it wrong as there are a lot of white space around icon
transistor also takes and renders a bitmap, but there are no white space

**Comment by PeterCxy** [comment]
> Is it possible to create the leftmost icon from shelter?

Why not? Just don't use the "freeze" feature and all your work app icons will appear normally in your launcher. Shelter's shortcut is only for frozen apps because those can't be shown normally by your launcher.

**Comment by PeterCxy** [comment]
> Moreover, I believe Shelter renders it wrong as there are a lot of white space around icon

Your launcher decides whether these should be any white space.

**Comment by 532910** [comment]
> launcher decides

Nope. Please check
y20k/transistor#210
https://source.android.com/devices/tech/display/adaptive-icons#known-issues

transistor had the same issue until it was fixed.
