### ISSUE TITLE
Is it possible to clone an app with its data?

### ISSUE THREAD

**Issue by 07416** [PeterCxy/Shelter#149]
My plan was to transfer all proprietary apps to the work profile which I'd disable when not in use, but Shelter doesn't carry the app data over. Is there an option to enable this functionality?

**Comment by PeterCxy** [comment]
No, there's no sane way Shelter can implement this even with root permission.

**Comment by Baerbeisser** [comment]
Alright, and the insane way? Can't i just manually copy the folder in /data/data/ somewhere? (Why with root not?)
Else would have to call my bank and re-register their f**ing app.
