### ISSUE TITLE
LOS 17.01 - not worked

### ISSUE THREAD

**Issue by seoguru4** [PeterCxy/Shelter#154]
Freezes on "Please wait, working profile is being created ...". Clean, freshly installed LOS 17.01.

**Comment by linsui** [comment]
https://github.com/PeterCxy/Shelter#known-issues

**Comment by PeterCxy** [comment]
You have to click on a notification for Shelter to finish set up since 1.5. You probably had your device on Do Not Disturb mode which blocked the notification. Try again without Do Not Disturb.
