### ISSUE TITLE
不小心把Shelter自身数据清空了

### ISSUE THREAD

**Issue by loco58** [PeterCxy/Shelter#159]
使用Shelter创建了一个app快捷方式，本来打算清空这个app的数据，结果，通过快捷方式上的app info进去没注意看，直接清空，才发现是Shelter的数据被清空。

现在打开Shelter，会提示已经有Shelter管理的work profile，如果继续的话，会把已有数据删除。有方式找回来么？

原本被Shelter冻结的app，在Android的app列表里也显示成“ 当前用户没有安装”，也没有卸载按钮，能否有方式让这些应用解冻？

**Comment by PeterCxy** [comment]
对不起，这种情况没有办法复原。
