### ISSUE TITLE
[bug] No short cut created

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#16]
When I try to add a unfreeze/launch shortcut for same apps it works (for example: orgzly, kolab ...) and for same it does not work (audible 
...)

**Comment by nr458h** [comment]
The same for the Batch freeze shortcut

**Comment by PeterCxy** [comment]
Could you describe in details how it "does not work"? It just doesn't appear on your launcher? What's your launcher and what's your ROM & device?

**Comment by nr458h** [comment]
Sorry forgot those infos :)
Yes it doesn't appear on my launcher. I use lawnchair on LOS 15.1

**Comment by PeterCxy** [comment]
I'm sure there was a similar problem with Lawnchair back when I was using LineageOS 15.1, that I couldn't create shortcuts from some of the apps I installed on my device. However I don't know if the problem still persists to this day.

Could you please, if possible, try with another launcher and see if the shortcuts will work?

**Comment by nr458h** [comment]
I was able to solve the problem. Indeed i'm able to create the shortcuts with trebuchet.

The problem is that I switched to lawnchair only one week ago, so there were already some shortcuts on the trebuchet launcher. After I removed those shortcuts (on the trebuchet launcher) I'm able to create the shortcuts back in lawnchair.

Probably this could be fixed by allowing more then one shortcut per app?

Thanks anyway for your support! And the great app :)

**Comment by PeterCxy** [comment]
@nr458h Oh I've encountered that problem when I first switched to Android 8.0 also. That's because Android only allows one shortcut per action on Android 8.0+ via its new shortcut mechanism. It is possible to allow more than one icon for one action, but that is not a standard behavior now.
