### ISSUE TITLE
Add 'Force stop' action

### ISSUE THREAD

**Issue by Drugoy** [PeterCxy/Shelter#160]
I don't really understand what 'Freeze' means and how to figure out if an app is frozen or not.
What I know is how to long tap onto an app icon and select App info > FORCE STOP. I know that this stops the application for sure.

Also, applications set up lots of hooks to different kind of actions (like switching mode (Standard > Silenced) or enabling/disabling Wi-Fi, etc.).

I am worried that some tracking (I'll just call them evil) apps will get executed this way. Is there a way to disable all hooks for stopped applications inside Work profile?

There used to be an awesome application [Autostarts](https://play.google.com/store/apps/details?id=com.elsdoerfer.android.autostarts) that exposed those hooks and if you had root permissions - it even let you disable those hooks.
Unfortunately, the app is long gone (became abandonware) and I don't know anything alike.

**Comment by PeterCxy** [comment]
"Freeze" is already more than just force stop. It completely disables the frozen application, including every single service / activity so that nothing can start it when frozen.

**Comment by Drugoy** [comment]
Then how come that after freezing an app the "App info > FORCE STOP" button is active (pushable)?

**Comment by PeterCxy** [comment]
@Drugoy Maybe your operating system is broken and does not allow profile manager apps to disable applications properly. After freezing, the application should not even appear anywhere in the app list or on the launcher (although on some devices you may still be able to see them marked as "not installed for this user"), let alone having "Force Stop" pushable. "Freezing" disables ALL components in the application, just like it gets uninstalled.

**Comment by Drugoy** [comment]
@PeterCxy turns out 'zzz' button in the application doesn't freeze anything until applications in work profile are marked for 'autofreeze' and now I see how freezing works (as if the app is deleted).
Finally figured that out how to use the app and I love it!
