### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by citydelver** [PeterCxy/Shelter#161]
Hello. Is it possible to create more than one work/secondary profile? I have shelter set and running fine in Android 10, so I have 2 profiles (main and work). I would like to have three. Can shelter currently do this?

In any case, thanks for this great app!

**Comment by fusionneur** [comment]
I don't think this is going to be on the roadmap anytime soon. There was an issue opened for this: #101
But I would also like this feature.

**Comment by PeterCxy** [comment]
This will be implemented once the multiple profiles feature of Android gets stablized into a public API. Until then, this will not be on the roadmap and this issue will be closed for now.
