### ISSUE TITLE
Image chooser as fake camera

### ISSUE THREAD

**Issue by JonnyTech** [PeterCxy/Shelter#162]
How does the fake camera feature work? I have apps that I want to present a default image rather than my video from the camera. The option within shelter seems ideal but apps can still see my video. Do I somehow have to enable it per app?

**Comment by JonnyTech** [comment]
Forgot my specs: Shelter 1.6 from F-droid, AOSP 10 on Redmi Go, rooted with superSU, microG replaced GApps.

**Comment by PeterCxy** [comment]
This feature is deprecated and was not designed for blocking camera access. Rather, it simply presents a fake Camera app which does not return a picture taken but rather lets you select an image from either the main or the work profile. This allows you to share images across profile boundary to applications that do not use the Storage Access Framework. As I have said before, this feature is not straightforward to use and is no longer usable on Android 11, so it is deprecated and will be completely removed.

**Comment by codethief** [comment]
I upgraded to Android 11 the other day and just realized that one of my favorite features of Shelter, the fake camera, no longer works. :( Are there any alternatives?

@PeterCxy Could you possibly elaborate on what exactly Android 11 does differently that prevents the fake camera from working? (I couldn't find any further info here in the Github repo.)

**Comment by PeterCxy** [comment]
@codethief Android has removed the ability to choose third-party camera apps when taking pictures on 11. Thus the feature no longer makes any sense.

**Comment by codethief** [comment]
Thanks so much for the quick response, @PeterCxy ! That's a bummer :(
