### ISSUE TITLE
Transfering files in to shelter!

### ISSUE THREAD

**Issue by im-sec** [PeterCxy/Shelter#166]
Can't find a way to transfer files in to shelter! 
Any idea on Android version 10?

**Comment by issu-shooter** [comment]
The developer said file shuttle feature is not supported in Anroid 10, I hope there's a way to get around this....

**Comment by im-sec** [comment]
I use FTP server to transfer between profile to work! But issue takes long time! Special for big size of file!

**Comment by fusionneur** [comment]
Can confirm file shuttle is inactive in android 10

**Comment by locuturus** [comment]
I'm not currently using Shelter (I set up Test DPC out of curiosity a while back and it's pretty hard to migrate) but even without File Shuttle can't you share intents into the work profile?  Then a receiver app like Save to File by XjCook (installed within Shelter) can handle the file from there?  That's what I do with Test DPC.

**Comment by PeterCxy** [comment]
File Shuttle is supported on Android 11, but will never be supported on Android 10 due to API limitations.
