### ISSUE TITLE
[feature request] batch unfreeze/launch shortcut

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#17]
It would be nice to be able to unfreeze several apps with one shortcut.
For example, when I use a specific app I also need orbot and the gallery.
At the moment I need to go to the homesreen three times.
Wished behavior would be to have a shortcut which unfreeze and launches all three apps at once.

Thanks for your effort - great app!

**Comment by PeterCxy** [comment]
This is really a great idea, but I now plan to implement real auto freezing first. I'll keep this open as a reminder for future development.

**Comment by PeterCxy** [comment]
This has been implemented in the master branch.
