### ISSUE TITLE
Can shelter protect users from Google tracking, analytics and telemetry inside apps?

### ISSUE THREAD

**Issue by ioogithub** [PeterCxy/Shelter#170]
I just sadly discovered that one of my mission critical github apps is full of Google tracking and analytics code.

If I install this particular app installed inside shelter will shelter, will it be able to  protect my phone from google tracking and privacy violations?

The particular apps has the following Google frameworks installed:

Google AdMob
Google Firebase Analytics
Google CrashLytics

I understand these 3 hook pretty deep into your phone. Can shelter help protect a user from these threats to privacy?

**Comment by PeterCxy** [comment]
No.
