### ISSUE TITLE
Feature request: support auto fill

### ISSUE THREAD

**Issue by ivysrono** [PeterCxy/Shelter#175]
Some discussion: https://github.com/Kunzisoft/KeePassDX/issues/526#issuecomment-738829227

> an external app service is never activated (regardless of the application with autofill) in the island profile settings (always returns to none).

**Comment by proletarius101** [comment]
As the linked page says, it have to be implemented in your autofill apps. A mitigation is to use your password manager's accessibility service, which is always cross-profile.
