### ISSUE TITLE
Shelter hangs on "Please wait..."

### ISSUE THREAD

**Issue by PeterCxy** [PeterCxy/Shelter#177]
If your Shelter setup process hangs on the "Please wait..." dialog, please make sure your device is NOT on Do-Not-Disturb mode, because you need to click on a notification to finish the setup process. If it still doesn't work after disabling Do-Not-Disturb, it probably means that there is an issue with your system, and it probably has nothing to do with Shelter itself.

EDIT: Since Shelter 1.7, the setup wizard should make it clear enough that you need to look for a notification. However, Shelter 1.7 and newer is not available from Play Store anymore. Please consider switching to either the official F-Droid version or the version on my personal F-Droid repo as linked in README.

**Comment by forever8938** [comment]
Shelter on oneplus 8T has this issue, while Island works perfectly.

**Comment by PeterCxy** [comment]
@forever8938 Have you tried the solution mentioned in OP?

**Comment by forever8938** [comment]
@PeterCxy What is OP? Do-Not-Disturb mode is already off, I don't see any notification from Shelter.

**Comment by PeterCxy** [comment]
@forever8938 Then the only possibility is that something in OnePlus's OS or the ROM you are running is actively preventing Shelter from starting. Maybe there's something that can be done to counter this but I currently don't really have much clue. However, I used to have a OnePlus phone but I have never run into this issue.

**Comment by gentoolinux** [comment]
I am having the same issue as @forever8938 with my Volla Phone. Shelter hangs on "Please wait...". Do-Not-Disturb mode is turned off. Is it possible to debug e.g. using adb what is causing the problems?

**Comment by PeterCxy** [comment]
@gentoolinux There might be, for example you can try to start the Shelter service inside work profile manually and see if that works. I think if DND is off, then all of these issues should be caused by some sort of auto-start supressing mechanism built into the OS, similar to dontkillmyapp.com.

**Comment by gentoolinux** [comment]
@PeterCxy Thank you. Could you please tell me how to start the Shelter service inside work profile manually? I have tried
```
255|k63v2_64_bsp:/ $ am startservice --user 70 -n "net.typeblog.shelter/.services.ShelterService"
Starting service: Intent { cmp=net.typeblog.shelter/.services.ShelterService }
Error: Not found; no service started.
```
but this did not work (70 is the ID of my work profile, identified using `pm list users`).

I have also tried to turn off doze using `dumpsys deviceidle disable` but I still see no notification.

While looking at the output of `adb logcat` I saw the following line
```
12-28 11:07:47.576   998  1828 W NotificationService: Toast already killed. pkg=net.typeblog.shelter callback=android.app.ITransientNotification$Stub$Proxy@9ffe2ad
```
I can provide full output if that helps.

**Comment by PeterCxy** [comment]
@gentoolinux Sorry I actually have no idea and I haven't done this myself. You need to invoke `net.typeblog.shelter.ui.DummyActivity` with action `net.typeblog.shelter.action.FINALIZE_PROVISION` in the profile to bring up Shelter inside the work profile for the first time.

**Comment by gentoolinux** [comment]
@PeterCxy I guess the command `am start --user 70 -a net.typeblog.shelter.action.FINALIZE_PROVISION -n net.typeblog.shelter/.ui.DummyActivity` should do the trick. Unfortunately it does not work:
```
k63v2_64_bsp:/ $ am start --user 70 -a net.typeblog.shelter.action.FINALIZE_PROVISION -n net.typeblog.shelter/.ui.DummyActivity
Starting: Intent { act=net.typeblog.shelter.action.FINALIZE_PROVISION cmp=net.typeblog.shelter/.ui.DummyActivity }
Error type 3
Error: Activity class {net.typeblog.shelter/net.typeblog.shelter.ui.DummyActivity} does not exist.
```
When I execute the command without the parameter `--user 70` I see the message `Shelter setup complete. Now restarting Shelter. If Shelter didn't start automatically, you may launch it again from your launcher` for a short time. But the app is still stuck at `Please wait while we prepare Shelter profile for you...`

It would be great if someone has an idea how to fix the issue. Here is the full output of `adb logcat` during the setup process: https://gist.github.com/gentoolinux/49d8df7bd242d8768671e09fc2972504

**Comment by gonejack** [comment]
一加上关闭电池优化就可以。但 shelter 本身问题是有点多，文件穿梭只工作了一回，之后就打不开工作资料内的存储目录了，每次打开文件管理器不是卡死就是闪退了，至于伪装相机那个，打不上勾。ROM是一加8T最新的氢。

**Comment by PeterCxy** [comment]
@gonejack 文件穿梭有问题多半是工作资料内的 Shelter 也被电池优化了。在 AOSP 和 LineageOS 上没遇到过任何问题。伪装相机已经不再支持了，之后会删除 (Android 11 取消了调用第三方相机 App 的能力)

**Comment by mhbear14** [comment]
Solution via ADB @PeterCxy  @gentoolinux 
#177

> follow the steps after you open shelter app and set up the work profile but are stuck  Please wait ...  and you don't receive a notification to complete the setup.

1. Get the user id of the work profile  by `adb shell pm list users` you will see 

> 	UserInfo{11:Work profile:1070} running
in my case the  work profile user id is 11 replace 11 with your work profile id in the below adb commands.

2. You need to install the shelter app to the work profile so  download the shelter  apk 

> Enter the correct filename of the apk file while pushing to the device Or rename the filename to sh,apk  to avoid typing long filename

Open adb in the same directory where the apk is present and run
`adb push sh.apk /data/local/tmp` 
 after you see the message file pushed 

3. Run this command `adb shell pm install --user 11 /data/local/tmp/sh.apk` 
> NOTE: Enter the correct user id of  your work profile  when  running the adb command
You will see a success message if not follow the steps 1 and 2  again 

4. You need to start the shelter app in the work profile run
 `adb shell am start --user 11 -a net.typeblog.shelter.action.FINALIZE_PROVISION -n net.typeblog.shelter/.ui.DummyActivity
`
Done

**Comment by Efenstor** [comment]
I can add that if you've installed Shelter from F-Droid then you already have the APK on your phone in the F-Droid APK cache. In this case the install command for the version 1.6 shall look like this:
`adb shell pm install --user 10 /data/data/org.fdroid.fdroid/files/Shelter-1.6.apk`
Note that you cannot install any other apk (e.g. downloaded from this GitHub repo) into the Work profile as its signature will be different from the one installed from F-Droid. At least I had problems with that.

**Comment by Jayotis** [comment]
Using Pixel 2XL with Pixel Experience android 12 and this seemed to happen for me.  I read the pinned comment and found the notification in the pull down, it did not have sound or layer itself over the app so it looked like the app was hanging.

**Comment by sketcharsh** [comment]
It hangs on my OnePlus 8T too and then I lost all my data because phone was stuck on reboot screen after that :(

**Comment by PeterCxy** [comment]
@sketcharsh It's most likely a bug of OnePlus's Android fork instead of Shelter. There is no way that Shelter can get your OS stuck in such a state. I've already warned in README that many Android vendor-specific forks have broken Work Profile implementations.

**Comment by PeterCxy** [comment]
@Jayotis That is how it's expected to work. Unfortunately on Android 12 I can no longer force the notification to be foreground anymore due to new technical restrictions (the notification has to be sent from the Shelter instance *inside* the work profile, but the one *inside* the work profile is not the one in the foreground (which is the one *outside*), and hence it cannot send foreground notifications)

**Comment by Jayotis** [comment]
Ok, thank you for the work you have done on this.  now that it is installed everything is working excellent.

**Comment by Iss-in** [comment]
I was having the same no notification alert after installation as well, did all the steps mentioned by @mhbear14 and was able to run the app. But now I cant install any app in work profile. I am not able to shift any app to work profile neither am able to install via an apk. any clue on why this is happening ?

**Comment by jasonnab** [comment]
Device: Zenfone 2
OS: Android 7.1.2 (custom ROM, LineageOS based)

I have a possibly different issue, where I get the notification, I can click it, I can see the Work Profile icon appear in the notification bar, but nothing happens. Shelter just sits at the final setup screen indefinitely.

If I force stop and launch Shelter again, it goes through setup from scratch (and will error out because of the existing work profile).

Have I missed a step, or is this the same issue as others are describing? 
I will additionally send this comment to the mailing list.
Thanks!

**Comment by Efenstor** [comment]
> Device: Zenfone 2 OS: Android 7.1.2 (custom ROM, LineageOS based)
> 
> I have a possibly different issue, where I get the notification, I can click it, I can see the Work Profile icon appear in the notification bar, but nothing happens. Shelter just sits at the final setup screen indefinitely.
> 
> If I force stop and launch Shelter again, it goes through setup from scratch (and will error out because of the existing work profile).
> 
> Have I missed a step, or is this the same issue as others are describing? I will additionally send this comment to the mailing list. Thanks!
Most likely the same issue. Try the solution described above: https://github.com/PeterCxy/Shelter/issues/177#issuecomment-783270352

**Comment by Efenstor** [comment]
> I was having the same no notification alert after installation as well, did all the steps mentioned by @mhbear14 and was able to run the app. But now I cant install any app in work profile. I am not able to shift any app to work profile neither am able to install via an apk. any clue on why this is happening ?

It looks like the permission issue. I can only suggest you trying another OS, such as LineageOS or its derivatives (such as LiR project). Everything works out of the box there and you get a more privacy-friendly system but you won't have any of the proprietary bells and whistles such as multiple cameras, Samsung Pay, etc. For another solution someone with a better technical expertise is needed.

**Comment by Iss-in** [comment]
it is a custom rom, [this](https://forum.xda-developers.com/t/23-march-2022-rom-a12-kosp-for-oneplus-7-official-guacamoleb.4358987) one in particular. Will try another A12 rom just to be sure

**Comment by PeterCxy** [comment]
@jasonnab I'll be honest, Shelter hasn't been tested on Android 7 for at least 2 years. It could very well be completely broken on 7. I'll try to test it at some point but no promises :)

**Comment by dream811** [comment]
> Solution via ADB @PeterCxy @gentoolinux #177
> 
> > follow the steps after you open shelter app and set up the work profile but are stuck  Please wait ...  and you don't receive a notification to complete the setup.
> 
> 1. Get the user id of the work profile  by `adb shell pm list users` you will see
> 
> > UserInfo{11:Work profile:1070} running
> > in my case the  work profile user id is 11 replace 11 with your work profile id in the below adb commands.
> 
> 2. You need to install the shelter app to the work profile so  download the shelter  apk
> 
> > Enter the correct filename of the apk file while pushing to the device Or rename the filename to sh,apk  to avoid typing long filename
> 
> Open adb in the same directory where the apk is present and run `adb push sh.apk /data/local/tmp` after you see the message file pushed
> 
> 3. Run this command `adb shell pm install --user 11 /data/local/tmp/sh.apk`
> 
> > NOTE: Enter the correct user id of  your work profile  when  running the adb command
> > You will see a success message if not follow the steps 1 and 2  again
> 
> 4. You need to start the shelter app in the work profile run
>    `adb shell am start --user 11 -a net.typeblog.shelter.action.FINALIZE_PROVISION -n net.typeblog.shelter/.ui.DummyActivity `
>    Done
I tried but have same error
adb shell am start -a "net.typeblog.shelter.action.UNFREEZE_AND_LAUNCH" -n "com.android.contacts/.ui.DummyActivity"
Starting: Intent { act=net.typeblog.shelter.action.UNFREEZE_AND_LAUNCH cmp=com.android.contacts/.ui.DummyActivity }
Error type 3
Error: Activity class {com.android.contacts/com.android.contacts.ui.DummyActivity} does not exist.

**Comment by PeterCxy** [comment]
This issue should not happen again after Shelter 1.8 -- it has been tagged a few days ago, but it hasn't been picked up by F-Droid yet. I'm going to close this issue and please do not add more responses here, unless it still happens with Shelter 1.8. If it still does, please start a new thread on the mailing list, rather than here on GitHub.
