### ISSUE TITLE
[bug] afwall settings lost

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#18]
I have some apps only running in the shelter. And if I configure the afwall settings for this app after a freeze and a reboot the afwall settings are lost.

As I can't configure an app in afwall without installed in the mainland I first need to reinstall the app in the mainland, than set the afwall settings for the sheltered version of the app and then i can youse the app again.

I think this is related to shelter because for example orbot works fine.

Still thanks, and now ne issues today :wink:

**Comment by PeterCxy** [comment]
I don't think Shelter could do anything about this. To other apps on your device, a frozen app in work profile just looks like being uninstalled. I think the AFWall just mistakenly regarded frozen apps as being removed for real. Shelter can't change this behavior of the system.

**Comment by nr458h** [comment]
There is already an issue in afwall
https://github.com/ukanth/afwall/issues/847
