### ISSUE TITLE
Bug Latest 

### ISSUE THREAD

**Issue by NSTAdventure** [PeterCxy/Shelter#183]
You can' uninstal pre cloned Apps:
-google play 
-gboard 
@PeterCxy 

And some apps that you clone manual is unable to uninstalled:
-gallery 

@PeterCxy

**Comment by PeterCxy** [comment]
There is no way to un-clone system apps due to Android API limitations. Besides, please go to the mailing list instead of here to report bugs.

**Comment by NSTAdventure** [comment]
> There is no way to un-clone system apps due to Android API limitations. Besides, please go to the mailing list instead of here to report bugs.

Wait do not close this instanly dude
Some apps still not able to uninstalled even it's not pre-cloned
Example i clone app gallery to shelter 
Now app gallery that are on shelter is unable to uninstalled :-(

**Comment by PeterCxy** [comment]
@NSTAdventure I have already answered your question: system apps cannot be un-cloned. Some system apps are not pre-cloned, but they are still system apps and cannot be un-cloned once it is cloned manually.

**Comment by NSTAdventure** [comment]
> @NSTAdventure I have already answered your question: system apps cannot be un-cloned. Some system apps are not pre-cloned, but they are still system apps and cannot be un-cloned once it is cloned manually.

I forgot to enable show all apps 🤦
