### ISSUE TITLE
Malware in shelter?

### ISSUE THREAD

**Issue by LinuxOpa** [PeterCxy/Shelter#188]
VirusTotal Scan:
Trojan:Script/Wacatac.C!ml in Shelter für Android = Shelter_base.apk

Please explain!

**Comment by LinuxOpa** [comment]
see #187

**Comment by proletarius101** [comment]
Don't you want to post a link to your scan report?

**Comment by citydelver** [comment]
![Screenshot_20210308_110756_org.mozilla.firefox_beta.jpg](https://user-images.githubusercontent.com/1512515/110306994-334b3980-7fdd-11eb-81ac-859c57f006f4.jpg)

![Screenshot_20210308_110747_org.mozilla.firefox_beta.jpg](https://user-images.githubusercontent.com/1512515/110307010-36dec080-7fdd-11eb-936d-3c0c8e975a00.jpg)

**Comment by proletarius101** [comment]
Are you aware of who is qihoo? https://en.wikipedia.org/wiki/Qihoo_360

**Comment by proletarius101** [comment]
And I can't reproduce the result for the F-droid version: https://www.virustotal.com/gui/file/2265f1831d267f0bca7ed61b3ff1f20c2c55351b942ab383b0da58d306d3a16c/detection
