### ISSUE TITLE
Feature. Faked google play service

### ISSUE THREAD

**Issue by cenapatop** [PeterCxy/Shelter#189]
On huawei devices without google play service I need the google services.

For the Satellit app and vim pay app.

Please insert a google play emulator

**Comment by andreasmjg** [comment]
Hi, I'd suggest checking out e.foundation at https://e.foundation 

This ROM has the feature you're mentioning pre-installed.

**Comment by PeterCxy** [comment]
It is not within the scope of Shelter to implement Google Play services replacement.
