### ISSUE TITLE
Is the developer ok?

### ISSUE THREAD

**Issue by citydelver** [PeterCxy/Shelter#191]
Hello. Just checking on the developer. Are you ok?

**Comment by dkunzler** [comment]
as stated in the readme he is not reading the github issues anymore...

this is a little bit unfortunate and he should then really disable github issues completely...

```Note: main repository: https://cgit.typeblog.net/Shelter/. The GitHub repository is only a mirror. I do not guarantee the GitHub repository will be up-to-date.

For bug reports and patches (pull requests), please use the following contact methods:

Mailing List (SourceHut): https://lists.sr.ht/~petercxy/shelter
Matrix Chat Room: #shelter:neo.angry.im
For translations, please use our Weblate interface at https://weblate.typeblog.net/projects/shelter/shelter/ to submit new translated strings for Shelter.

On GitHub, any new issues or pull requests will not be read or accepted. Please use the contacts listed above.```

**Comment by PeterCxy** [comment]
> he should then really disable github issues completely

I am going to do this, but as of now there are some backlog on the github issue list that still needs to be fixed. I hope GitHub had a "lock issue list" feature...
