### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by NSTAdventure** [PeterCxy/Shelter#192]
Request:
1.Ability To Enable Owner (Admin Mode)
-You Can Freeze Apps Both In Work Profile And Outside Profile

2.Ability To Protect User By Disabling ADB Access 
-(If Owner Or Admin Mode Activated Shelter Can Protect Both Inside And Outside Work Profile)

Also I Want To Ask 
How Do I Change Work Profile Name? @PeterCxy

**Comment by PeterCxy** [comment]
1. No, this is not anywhere on the roadmap of Shelter.
2. No, this is not anywhere on the roadmap of Shelter.
3. Name of the Work Profile probably cannot be changed.
