### ISSUE TITLE
Install OpenGApps or MindTheGapps to Work Profile Only?  

### ISSUE THREAD

**Issue by powline99** [PeterCxy/Shelter#200]
How do you Install OpenGApps or MindTheGapps to the Work Profile Only? I searched the readme, issues, XDA, Youtube, and Reddit and could not find anything. I want to keep my "private"  profile with Lineage / MicroG only and Work Profile with Minimal Gapps. 

Any ideas?:

I found this but don't know how to fastboot boot a Work Profile.

adb push android.apk /data/local/tmp

adb shell pm install --user 10 /data/local/tmp/android.apk

My settings:

Users:

UserInfo{0:Owner:c13} running

UserInfo{10:Work profile:1030} running

3) Would Installing Magisk work and the opengapps module for it. If so How do I flash Magisk for a work profile

Thanks!

**Comment by PeterCxy** [comment]
It is not possible to do so as of now (at least without some serious hacking in the system).

**Comment by willheisenberg** [comment]
Any progress on that !?

**Comment by PeterCxy** [comment]
@willheisenberg There is no progress to be made here from Shelter side. It's simply not something doable as an app.

**Comment by willheisenberg** [comment]
ok but in graphenos it is possible because of there apps store. So actually on one system it is aleady possible. But i would like to stay with lineage

**Comment by PeterCxy** [comment]
@willheisenberg Then you'll need to ask Lineage developers. This is an OS feature, not an app feature, and there is 0 things that can be done from Shelter side.
