### ISSUE TITLE
Copying files to Work Profile renames files to *.null 

### ISSUE THREAD

**Issue by twisteros** [PeterCxy/Shelter#201]
I installed the Shelter app and created a new work profile.
Then I enabled "File shuttle", tapped "Open Document UI" and copied a few files from the main profile.
All the files got renamed to *.null ie. file.gpx.null.
The "Rename" option in the the File UI is greyed out.
How can I get files copied  without auto-renaming?

**Comment by linsui** [comment]
See https://github.com/PeterCxy/Shelter/issues/132
