### ISSUE TITLE
[feature request] widget creation

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#21]
It would be nice if I could use the widgets from the apps in the shelter

**Comment by PeterCxy** [comment]
This will be looked into after the next release.

**Comment by marlid91** [comment]
Any news on this?

**Comment by PeterCxy** [comment]
@marlid91 it will be included in the next release if nothing goes wrong. I am busy for my finals these days, and development will resume after that (~10th Jan)

**Comment by PeterCxy** [comment]
Implemented on master branch.

**Comment by nr458h** [comment]
Thanks a lot!!!

**Comment by riedel** [comment]
Has anyone confirmed this is working as expected?

In Trebuchet on Lineage OS 16 with Shelter 1.5 I am seeing only 1x1 widgets in the widget list and they don’t seem to appear after dragging them to the desktop.

Would be great if someone could name me a widget app/launcher combination I could test this with.

**Comment by riedel** [comment]
Sorry, I finally found out that you have to allow it manually by selecting the app inside shelter thx. Works like a charm!!

I am still irritated that some 1x1 widgets showed up in the list without any extra permissions.
