### ISSUE TITLE
Shelter is dead and the creator left the repository. No need to ask for bug fixes.

### ISSUE THREAD

**Issue by Thewisem** [PeterCxy/Shelter#211]
Shelter has been dead for some time even though people have been giving issues. I think the lead dev left the app as is and didn't come back. I mean it has been requiring a long amountof bugfixes but so far I haven't seen him interact at all recently so I think he left.

**Comment by rzr** [comment]
May this be maintained by @abandonware community ?

https://rzr.github.io/rzr-presentations/docs/abandonware

Please ping me if interested to xfer this project to @abandonware org

**Comment by andinus** [comment]
> Shelter is not abandoned. I am just a bit busy with other things in my life in recent months. The 1.7 release is actually only blocked by Google Play policies on file access right now, and I'm actually thinking about ditching the Google Play version and release exclusively on F-Droid (with a custom repository signed with my own keys for former Google Play users to migrate smoothly). I'll try to make a decision and push an update within the next two months or so.

- https://lists.sr.ht/~petercxy/shelter/%3C1109953855.139497.1626631754976%40office.mailbox.org%3E

**Comment by PeterCxy** [comment]
As explained on the mailing list, it is not dead as far as I am concerned. I am not working full-time on this single project, and donations from this single project is not nearly enough to support my life. In addition, the GitHub repository is simply not monitored regularly at all -- I have already stated this __clearly__ in the README. If you want __any__ response from me, please use the mailing list.
