### ISSUE TITLE
Hypothetical problem about sandboxing with shelter in grapheneos?

### ISSUE THREAD

**Issue by boistordu** [PeterCxy/Shelter#230]
Hi,

First, I'm really grateful for the work you've put through in your app. 

I'M not sure about the title, I'm not too sure also that's the responsibility of your app but there is a correlation I think and also I will relink this issue to a repository of grapheneOS too if I find the right one. 

I'm relatively new to grapheneOS but I've used your app for a long time but under divestOS which is very different. 

I've encountered an odd problem which puts me under pressure to ask a few questions to be sure that I'm not wrong. 

First, Is a work profile under shelter as contained than a user profile in grapheneOS (which is supposed to have 0 communications with other profiles and even less apps since everything is supposed to be sandbox)?

I was using deezer under my owner profile. I've created a work profile with shelter, and installed GFS and the others dependencies. Deezer was working before I do this on the personal part of the owner profile. 
But after I did this, apparently somehow deezer detected the presence of GFS because It gave me an error message when launching the app just afterwards "that deezer was not going to work without GFS and it was updating".
It's not coming from a problem of an update of deezer since it's still working on my divestOS setup. 

I will provide the screenshot of the error. 

So since GFS is supposed to be sandboxed in grapheneOS and even more since it's in shelter, how deezer has detected the presence of GFS ?

Thanks in advance 
Best regards![image](https://user-images.githubusercontent.com/9523075/158587056-3ff7cccb-c5ef-4e71-91e8-7b38a1afbd9e.png)

**Comment by PeterCxy** [comment]
Work profiles are not true sandboxes. All apps you install as part of either profile will appear as an "uninstalled" app in the other profile. It only prevents data exchange between the profiles directly, but other than that, nothing much. Apps can certainly detect whether such an "uninstalled app" exists.
