### ISSUE TITLE
Not Getting Notification During Setup on Android 13

### ISSUE THREAD

**Issue by FrenchToucan** [PeterCxy/Shelter#236]
The final step out of the setup process is to click the notification in the shade but on Android 13 (final on Pixel 6), it does not appear. Even manually adding the notification permission to Shelter before setup she's not fix the issue.
As a result, The Work profile is partially setup and must be deleted from the Android Password & Accounts screen.

**Comment by mhamzas** [comment]
Facing the same issue. Any workaround?

**Comment by PeterCxy** [comment]
I've just upgraded my own devices to Android 13 and will be working on a fix and a new release ASAP.

**Comment by PeterCxy** [comment]
There is now a dev version on my personal F-Droid repo (fdroid.typeblog.net) that should work on Android 13. Please test it out and I will make it a full release after a few more adjustments.

**Comment by FrenchToucan** [comment]
> There is now a dev version on my personal F-Droid repo (fdroid.typeblog.net) that should work on Android 13. Please test it out and I will make it a full release after a few more adjustments.

Just installed it on a Pixel 6 Pro with Android 13 and it worked. I was able to complete work profile setup and install apps on the profile. Thanks for fixing! Love that you created this app!

**Comment by mhamzas** [comment]
> There is now a dev version on my personal F-Droid repo (fdroid.typeblog.net) that should work on Android 13. Please test it out and I will make it a full release after a few more adjustments.

Thanks Peter - I did install another app named "ISLAND" which worked fine for A13. Just wanna know can I install this new version and replace it without removing the work profile or will have to start scratch?

**Comment by PeterCxy** [comment]
@mhamzas Unfortunately it is impossible to replace the work profile manager without deleting and re-provisioning the profile.

**Comment by EmRowlands** [comment]
> There is now a dev version on my personal F-Droid repo (fdroid.typeblog.net) that should work on Android 13. Please test it out and I will make it a full release after a few more adjustments.

Is there any plan for when this release might happen?

**Comment by PeterCxy** [comment]
It will likely happen this week.

**Comment by benmordecai** [comment]
I'm having this problem as well. I was using the latest on F-droid (1.7) until just now when I uninstalled it. I would be happy to install the private version, but it has been 7 days since it the last comment, so if it is about to be released I could just wait.

**Comment by PeterCxy** [comment]
@benmordecai Well, even if I release it right now, it would take at least a few days to one week for F-Droid to complete their build and signing process. If you see me tagging a release, then you can expect to see it in the main F-Droid repository the same day next week.

**Comment by benmordecai** [comment]
Thanks, I just realized that this is a repo rather than an individual download, so that makes it a no-brainer to sign up for your personal repo. Went through with the install and succesfully got it set up on a Pixel 6a for Graphene on Android 13. Getting ready to start setting up the apps.

**Comment by dwalia** [comment]
@PeterCxy Thanks for the package. It is highly appreciated. I just installed GrapheneOS yesterday on my P6P and was looking forward to use Shelter. After the same issues the other users experienced here. I just added your repo and tried to install either of the v1.8 of shelter (1.8, 1.8-dev-1, 1.8-dev-2) unfortunately all installation failed.

**Comment by dwalia** [comment]
@benmordecai Thank you for this. I assumed some related issue. Thus, I have uninstalled F-Droid and then tried to install Shelter v1.8 from the repositories by PeterCxy. Unfortunately, the error persits. Moreover, I tried to installed shelter from the PlayStore (knowing that it is an older version) which failed with a similar error: "You cannot install this app because another user has already installed an incopatible version on this device." - Seems to me as there is something left over of the old Shelter installation which has to be wiped before reinstallation. Didn't expect this to be possible on android. I have no clue how to solve this.

**Comment by PeterCxy** [comment]
@dwalia The previous Shelter installation has probably created a non-functional work profile. Just remove that from Settings - Accounts and you will be able to install the other Shelter version.

**Comment by dwalia** [comment]
@PeterCxy Awesome. Thank you! I wasn't aware of this.

**Comment by PeterCxy** [comment]
Also I am going to close this issue because I have tagged the 1.8 release, and it is beyond my control when it will enter the F-Droid repository.
