### ISSUE TITLE
How to update cloned apps?

### ISSUE THREAD

**Issue by Freekers** [PeterCxy/Shelter#28]
First of all, thank you very much for Shelter. It's a great FOSS Sandboxing solution for non-root Android users.

I am having some trouble (understanding) how to update cloned apps. Suppose I have cloned an app to my work profile; how do I update the clone?

I saw that I can also remove the Original app while keeping the clone, but then the question still remains: How to update the clone?

Thank you!

**Comment by PeterCxy** [comment]
You can clone your preferred app store into the work profile.

**Comment by PeterCxy** [comment]
And if the app exists both outside and inside the work profile, they will also be updated together; a clone can't be of different version with the other side.

**Comment by chilliger** [comment]
> 
> 
> You can clone your preferred app store into the work profile.

Does not work for me https://github.com/PeterCxy/Shelter/issues/24#issuecomment-527125660. Aurora uses the root method to install apps. Could this be the issue?
