### ISSUE TITLE
Android 6 Marshmallow support?

### ISSUE THREAD

**Issue by gizmo21** [PeterCxy/Shelter#29]
Are there any plans on enabling this app for Android 6.0.1++ as Island seems to be or would it be too complex to support another version.

Asking cause BlackBerry Priv won't get OS upgrade anymore.

**Comment by PeterCxy** [comment]
Nope, there is currently no plan to backport Shelter to Android < 7.0, partly because that I started out the project using a lot of JDK 7 features.

**Comment by gizmo21** [comment]
Thx for your answer I just wanted to know I you plan it, but I understand that for single dev this is too much to ask for if it was not on your list already.
