### ISSUE TITLE
Cannot remove app from profile if it is a system app

### ISSUE THREAD

**Issue by SkewedZeppelin** [PeterCxy/Shelter#3]
If an app is installed to /system and cloned to the Work profile it cannot be removed.
Is this a limitation of Android for Work or of Shelter?

**Comment by PeterCxy** [comment]
This is expected. The Android API allows a profile manager to enable a system app in a work profile, but the API is irreversable.

**Comment by Caaruzo** [comment]
I encountered the same issue with messages APP. is there an way to remove? Or is the only way to freeze it? Maybe a work arround?

Greetings.
