### ISSUE TITLE
Obtainium unable to install the 'latest' version - currently is still set to 1.6 ?

### ISSUE THREAD

**Issue by K-J-VV** [PeterCxy/Shelter#309]
Only able to install actual latest version (1.9.1) via F-Droid.

Obtainium downloads via Github directly and references the 'latest' tag, which is tied to version 1.6 ?

Install via Obtainium should work once this is corrected

**Comment by PeterCxy** [comment]
@tegridyfarmer Does Obtanium support installing from Gitea / Forgejo releases? Doing GitHub releases is a hard no but I can upload apks to the release page of my Forgejo instance, which hosts the canonical version of this repository.

**Comment by vvirtues** [comment]
this is possible using the third party repo btw

**Comment by vvirtues** [comment]
[Install Link](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22net.typeblog.shelter%22%2C%22url%22%3A%22https%3A%2F%2Ffdroid.typeblog.net%3FappId%3Dnet.typeblog.shelter%22%2C%22author%22%3A%22PeterCxy's%20F-Droid%20Repo%22%2C%22name%22%3A%22Shelter%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22appIdOrName%5C%22%3A%5C%22net.typeblog.shelter%5C%22%2C%5C%22pickHighestVersionCode%5C%22%3Atrue%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22FDroidRepo%22%7D)

**Comment by PeterCxy** [comment]
The GitHub release of F-Droid 1.6 has been deleted in order to avoid further confusion.

Shelter is NOT available on GitHub.

I am closing this issue because the GitHub repository is not supposed to be used as a channel of communication. I am going to open up Forgejo issues on the Forgejo instance, and if you would like to keep this tracked for the future, please go to there.

In the mean time, please use the official mailing list for discussion.
