### ISSUE TITLE
Privacy guard for apps in shelter

### ISSUE THREAD

**Issue by marlid91** [PeterCxy/Shelter#31]
Hello, it seems like Privacy Guard for Lineage OS 15.1 doesn't work for the apps inside shelter (or at least I can't access their settings). If I go to settings - security & privacy - trust - privacy guard then the apps inside shelter don't show up. If I go under the advanced tab they do show up:

https://i.imgur.com/dJpx11g.png

Messenger lite and google maps is in shelter

If I press on Messenger lite the settings look like this:

https://i.imgur.com/pNuZ260.png

I've tried to copy Android's settings app into shelter (it says it succeeded), but it doesn't show up. 

Is this a limitation in Android? Lineage OS? Shelter?

**Comment by jmue** [comment]
I can only speek for LOS 14.1. There I get a selection dialog like this while clicking on pivacy guard. 

![screenshot_20181015-211929](https://user-images.githubusercontent.com/898577/46973213-d9badb00-d0c0-11e8-9e34-8ca1f55901e5.png)

**Comment by PeterCxy** [comment]
This is a bug of the Privacy Guard itself. Shelter can currently do nothing about this because I haven't introduced root / adb features yet.
