### ISSUE TITLE
Switch to Material You design

### ISSUE THREAD

**Issue by tegridyfarmer** [PeterCxy/Shelter#315]
Material You allows for personalization by adapting a user's system colors into the design.
For example Obtainium has a setting that changes the application color based on the defined system colors.
Material You also allows a consistent user experience across devices, which improves usability and navigation.

**Comment by vvirtues** [comment]
check the pinned comment. he doesnt like to check here

**Comment by PeterCxy** [comment]
Latest shelter is already Material You.

GitHub issues aren't usually checked. Closing.

**Comment by vvirtues** [comment]
Where?

**Comment by PeterCxy** [comment]
The only official publishing channels are F-Droid official and my personal F-Droid repository at https://fdroid.typeblog.net. If the UI is not Material You, that version you are using is at least more than 2 years old.
