### ISSUE TITLE
The new clone app haven't a root access

### ISSUE THREAD

**Issue by giupardeb** [PeterCxy/Shelter#32]
I use CheatDroid to edit some parameters of my apps. When I clone an app with Shelter, CheatDroid doesn't show me the new cloned app. I tried to clone CheatDroid, but it doesn't find a root permission.
Any solutions?
THX

**Comment by PeterCxy** [comment]
Your root manager has to support multi-user for this. Magisk Manager has a setting that has to be enabled for this to work.

As a side note, most apps that do need root won't implement its features in multi-user mode correctly. Always be careful when using root inside a secondary user.
