### ISSUE TITLE
[feature request] include tor routing

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#33]
As it is said in the readme, this app is for example to use big brother apps or apps which don't respect the privacy of it's user.
So in my opinion it would be create if I were able to route within shelter apps through the tor network.

Maybe this is related to #27. 

I hope it is understandable and clear what i tried to express;) 

Edit: 
Probably this could be done by making it possible to route the traffic through an vpn and I can select from the list of installed VPNs ?
So if I install orbot in the mainland I could select apps to use orbot as a VPN service.
Understandable?

**Comment by marlid91** [comment]
You can do this by installing Orbot in the work profile and using it as a VPN

**Comment by nr458h** [comment]
@marlid91 I know but in my humble opinion it would be nice to have that managed with shelter.
- because one app less to keep updated
- no second App running all the time in the background even if not needed
- in addition only when an app is unfreezed it can be managed in orbot

Maybe there are more advantages to integrate that.

**Comment by nr458h** [comment]
After using the app quite a long time this is not a feature I would ask for anymore.

Thanks for the great app!
