### ISSUE TITLE
[Feature Request] Allow changing permissions of Google apps

### ISSUE THREAD

**Issue by mlaradji** [PeterCxy/Shelter#35]
## Setup
Shelter: 1.3
Phone: Samsung A5 (2017)
Samsung Experience: 9.0
Workspace: 3.1
Knox: 3.1; API level 25; TIMA 3.3.0
Android: 8.0.0
Android Kernel: 3.18.14

## Issue
Currently, many Google apps in the Shelter Workspace, such as Google Play Services, have fixed permissions that cannot be changed. Attempting to change it results in the following prompt:

> Unable to perform action
 You do not have permission to perform this action. Contact your organization's IT administrator for more information.

The administrator is correctly shown to be Shelter, and this is indeed only a problem in the Workspace. I can change permissions or disable Google Play Services (for example) outside of the Workspace with no problem.

## Why is this problematic?

Well, Google Play Services, for one, requires many permissions, such as camera and microphone access, that are huge privacy concerns. Although one can switch off the Workspace, it is desirable that those permissions are not provided even when the Workspace is switched on.

## Proposed Solution
One or both of the following could be implemented:
1. Allow changing the permissions of those apps.
2. Have a main switch inside Shelter to turn on or off specific permissions. For instance, something like "Allow apps in Workspace to access camera" could be useful.

## Comments
It is possible that this is a limitation of Workspace that cannot be circumvented.

**Comment by mlaradji** [comment]
I've installed the latest version of Shelter and this seems to have been fixed. My current version info is:
Shelter: 1.4.1
Phone: Samsung A5 (2017)
Samsung Experience: 9.0
Workspace: 3.1
Knox: 3.1; API level 25; TIMA 3.3.0
Android: 8.0.0
Android Kernel: 3.18.14

As such, I will close this issue. Many thanks to the development team. :+1:

**Comment by SieNamaer** [comment]
Hi,

May I ask how you did that? That is, how did you disable the permissions for google play services (for example) in the shelter workspace?

I am currently running Shelter version 1.4.1 on a Samsung S10 and when I try to disable permissions, it displays the same message as you mentioned above about '..Contacting your organization's IT..' 
I cannot seem to find the option to either directly disable the permissions from the apps (in my Work Profile) or from within Shelter.

Would appreciate the help. Thanks a lot.
