### ISSUE TITLE
[Feature Request] Support directly installing APK

### ISSUE THREAD

**Issue by SkewedZeppelin** [PeterCxy/Shelter#4]
Currently to install an app into the Work profile you have to do one of the following:
- install an app, then clone it
- clone an app store (F-Droid) into it, then install from the store

the ability to directly install an APK through Shelter into the Work profile would greatly simplify that process.

**Comment by axxx007xxxz** [comment]
I've encountered the same on Island, you might try cloning software installing application and then "opening" the APK file with it (it should be marked by Android for Work logo).
I agree that the ability to do this directly through Shelter would be better.

**Comment by PeterCxy** [comment]
implemented in master branch.
