### ISSUE TITLE
Adding apps to auto freeze

### ISSUE THREAD

**Issue by beeshyams** [PeterCxy/Shelter#5]
It is not clear how the apps in this list get populated. Neither is it displayed nor an option to add apps

**Comment by PeterCxy** [comment]
Sorry but I didn't quite get the question here?

**Comment by beeshyams** [comment]
I should be sorry. Figured it out. Apologies. Closing the issue

**Comment by beeshyams** [comment]
I should be sorry. Figured it out. Apologies. Closing the issue
