### ISSUE TITLE
 Is a mobile phone only have one working directory?

### ISSUE THREAD

**Issue by penhauer-xiao** [PeterCxy/Shelter#50]
Samsung note8, has been installed on the island, now installed Shelter, the following tips, why? Is a mobile phone only have one working directory?

![image](https://user-images.githubusercontent.com/6280121/52909802-1b56cf00-32c9-11e9-9441-cbf8dffd8dc0.png)

**Comment by PeterCxy** [comment]
Exactly. It is how work profiles work.
