### ISSUE TITLE
请问可以将已冻结的应用在工作区显示图标么

### ISSUE THREAD

**Issue by whengrun** [PeterCxy/Shelter#52]
您好，我目前将大部分的国内应用安装在工作区内，平常都处在自动冻结的状态。现在每次打开应用时需要打开shelter在选择需要的应用或者就是在桌面上放置快捷方式,不知能不能增加个开关用于保留已冻结应用在工作区的图标。

**Comment by PeterCxy** [comment]
系统限制无法实现。
