### ISSUE TITLE
开启了以后提示工作模式被您关闭

### ISSUE THREAD

**Issue by qwazx** [PeterCxy/Shelter#57]
删除了重新开启软件设置也不行，手机是三星S10+，但是工作模式应该是开启的。其他没修改，就是安装开启了软件然后自动设置完毕之后，下一次进入就会这样

**Comment by linsui** [comment]
相同的情况。Rom 是 PHH AOSP

**Comment by linsui** [comment]
在打开 Shelter 后，首先会提示创建工作资料，然后提示删除现有工作资料。我发现这个工作资料已经是由 Shelter 管理的了。如果此时选择删除则会出现上述状况。如果选择取消，则可正常使用 Shelter。

**Comment by qwazx** [comment]
我没有提示，而是软件直接打不开，闪退的状态，他没有给我提示删除现有工作资料的选择

**Comment by linsui** [comment]
你可以卸载重装试试。我取消设备管理权限后重新打开 shelter ，然后就出现了这些提示

**Comment by qwazx** [comment]
好的，谢谢，我试一下

**Comment by qwazx** [comment]
测试无效，不行

**Comment by PeterCxy** [comment]
可能与 05492af180180c985590e467b7f7e97ae2909b86 有关。由于已经有另一个 issue 追踪同一个问题，这个暂时关闭。
