### ISSUE TITLE
Support Can't install on LOS 14.1

### ISSUE THREAD

**Issue by nr458h** [PeterCxy/Shelter#6]
Hi I use a Samsung Galaxy S6 edge with LOS 14.1 and I'm not able to install the app via F-droid. It shows me a notification: no compatible version.

Is Android 8 or higher required because I couldn't found anything in the readme.
At the moment Island works on this phone.

Thanks in advance

**Comment by PeterCxy** [comment]
It will be able to run on Android 7.0 the next release.

**Comment by nr458h** [comment]
Thanks :clap:
