### ISSUE TITLE
Cannot initialize on Android 9.0 Pie

### ISSUE THREAD

**Issue by da-h** [PeterCxy/Shelter#62]
Hi @PeterCxy,

I just stumbled upon your app.
Unfotunately It says "*You have to grant Device Admin permissen for Shelter to work. Please try again.*" after I press "*Activate this device admin app*".

If I check manually, the list "*device admin apps*" is empty, so unfortunately I cannot add Shelter.
My setting is as follows: *AOSP 9.0 Pie (r34)*.

**Is this problem related to my setting (Android 9.0)?**

Best,
*da-h*

**Comment by PeterCxy** [comment]
Sorry I haven't seen this problem before. What exactly is your device running? Is it the Android on Pixel, or is it some third-party "AOSP" build for non-official devices?

**Comment by da-h** [comment]
Thank you for your response.

I use the official AOSP source tree given by the [Sony Open-Device Program](https://developer.sony.com/develop/open-devices/) using their precompiled kernels.
I did no changes to any source, but compiled it myself (using the [official guide](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0)).

**Comment by PeterCxy** [comment]
I've got no idea, but it is possible that this may be a problem introduced by either sony AOSP fork or the new patch of Android 9.0. I'll check after I merge the latest patches of AOSP to my device. Also, it will also help if anyone else here could reproduce this problem.

**Comment by da-h** [comment]
Thank you for your help.
Let me know if I can help you to solve this problem.

Best,
*da-h*

**Comment by da-h** [comment]
Dear @PeterCxy,

I found the solution to the issue on [stackoverflow](https://android.stackexchange.com/questions/171907/apps-not-appearing-in-device-administrators) (where else ¯\\\_(ツ)\_/¯ ).
The problem was that Android requires **device-admin apps to be installed to internal storage**. However, my Android 9 installation used the SD card by default.

Best,
*da-h*

**Comment by Roxxor91** [comment]
Hi!
I also just stumbled over that issue. Now selecting the internal storage it works. May this be added to the FAQs? I think that would help many people to sort out issues.
