### ISSUE TITLE
系统升级后，无法解锁工作资料

### ISSUE THREAD

**Issue by yikuo123** [PeterCxy/Shelter#63]
emui9.0升级了安全更新后，提示工作资料已锁定，需要输入锁屏密码解锁。输入正确的锁屏密码仍然提示密码错误。

**Comment by PeterCxy** [comment]
工作资料锁定只有ROM能够控制，请向您的手机厂商反馈该问题。

**Comment by yikuo123** [comment]
> 工作资料锁定只有ROM能够控制，请向您的手机厂商反馈该问题。

第一次碰到这问题，我移除了工作资料，然后所有工作资料里的数据没有了。
没过多久，又有了一次安全更新，更新后又出现这问题。联系了多次华为客服，最后给出的答复是需要我输入创建工作资料时候设置的密码（客服说是研发的答复）。但我使用shelter创建工作资料时并没有输入任何密码，shelter是否使用了某个默认密码而没有让用户输入？
现在除了输入正确的密码没有其他办法可以解锁工作资料了。
