### ISSUE TITLE
Can applications inside the work profile be isolated from each other?

### ISSUE THREAD

**Issue by miquecg** [PeterCxy/Shelter#64]
We do have control of the data we want to be have in the work profile, but once there, it's available for all applications inside. It would be nice to have even more control, at profile level, but not sure if this would be possible.

Some thoughts that came to my mind:
- Sub-profiles
- Profiles + fake data provider

**Comment by PeterCxy** [comment]
It is not possible with the current Android work profile APIs. To achieve this level of isolation, a container-based virtualization must be implemented, which is not something Shelter plans to do.

**Comment by miquecg** [comment]
Thanks for your reply. No matter how, this app is great 👍

Side note: *apparently* this feature is planned for Island later this year. No idea on how is going to be implemented if such thing happens.
