### ISSUE TITLE
[Feature] Ability to give fake data to apps

### ISSUE THREAD

**Issue by JonasNo** [PeterCxy/Shelter#67]
Developers will catch on to app isolation and detect it can't access the contact list and such. So why not give it a fake contact list? If the app wants to know where you are on the planet then give it fake gps route (or several routes to choose from or even an automatically generated route) so it looks like you are driving or walking.

The intrusive app gets data to play with and you are happy that the app is usable and doesn't nag you for data.

**Comment by PeterCxy** [comment]
this is not possible with android work profiles, thus not a goal of  Shelter.
