### ISSUE TITLE
Can Shelter run simultaneously with Secure Folder?

### ISSUE THREAD

**Issue by Shadowspear123** [PeterCxy/Shelter#72]
Hi,
The Readme states that shelter cannot work at the same time as another app that uses workspace. My question is if Samsung Secure Folder uses workspace, and if the two can run at the same time perfectly. I activated both to try and they both seemed to work fine, so i'm wondering if something is going on behind the scenes.

**Comment by PeterCxy** [comment]
Sorry, I am not really sure about Samsung's implementation details, and we have had users who messed things up by doing so. Anyway I don't think this issue is really related to Shelter itself.
