### ISSUE TITLE
Background activity launch blocked in Android Q

### ISSUE THREAD

**Issue by Mygod** [PeterCxy/Shelter#73]
Tested on Android Q beta 4 emulator.

Doc: https://developer.android.com/preview/privacy/background-activity-starts

From Island:

> **For Android Q beta, please enable "Allow background activity starts" in system "Settings - Developer options".**

**Comment by Mygod** [comment]
This would be resolved using device owner mode:

> The app is a device policy controller running in device owner mode. Example use cases include fully managed enterprise devices, as well as dedicated devices like digital signage and kiosks.

**Comment by PeterCxy** [comment]
Using device owner mode would not be a good option for something like Shelter. I'll look into this issue once I have Android Q up and running on my device.

**Comment by PeterCxy** [comment]
From Android docs:

> The app has been granted the SYSTEM_ALERT_WINDOW permission by the user.

Maybe this could be a solution.
