### ISSUE TITLE
华为EMUI9闪退

### ISSUE THREAD

**Issue by WooDragon** [PeterCxy/Shelter#75]
EMUI9
首先是卡在为您准备shelter，通过给足权限开放自启动等解决了。
然后创建成功后app自动关闭了，然后再启动就一直闪退……
尝试删除工作资料，卸载后重新配置，也是一样的情况～

**Comment by Hbzzw** [comment]
不一定支持魔改系统，开发者说过了

**Comment by PeterCxy** [comment]
不支持华为。
