### ISSUE TITLE
Merge Changes from Island 3.7.5: Root/Knox fix

### ISSUE THREAD

**Issue by ahdr** [PeterCxy/Shelter#77]
Island has introduced several changes and bug fixes that enables rooted Samsung devices to work.

* v3.7: Fixed Island setup with root.
* v3.6: Island can now coexistent with OEM-internal managed profile. (e.g. Samsung Secure Folder).

Please merge these upstream changes into your forked project. Note: there could be other changes required other than just the above mentioned.

**Comment by PeterCxy** [comment]
Shelter is not a fork of Island. Due to license issues, we cannot directly merge stuff from Island. And I do not have anything to test for Samsung devices, so there is no way I could merge those changes.
