### ISSUE TITLE
Issue with the install of F-droid

### ISSUE THREAD

**Issue by arnauldb** [PeterCxy/Shelter#81]
Hello,

I installed F-droid (after having installed Shelter and after having created a work profile with Shelter) as a system application on my Asus phone flashing https://f-droid.org/packages/org.fdroid.fdroid.privileged.ota/ with twrp then installing this apk https://f-droid.org/packages/org.fdroid.fdroid.privileged/

When I boot my phone I realized F-Droid also installed by itself in the work profile I created with Shelter. How to uninstall F-droid from my work profile in Shelter? Does the fact to have F-droid installed in the work/Shelter profile cause any security issue?
Can I leave it like this (not using F-droid in the work profile)?

I guess a way would be to install F-droid as a system app before installing Shelter.

Thank you.

**Comment by PeterCxy** [comment]
You cannot remove a pre-installed system app from work profile. There's nothing Shelter can do about it.
