### ISSUE TITLE
Not work on Honor 8 with emui 8 & android8.0

### ISSUE THREAD

**Issue by wkable** [PeterCxy/Shelter#83]
My phone is Honor8, EMUI8.0 and Android 8.0. I install the "Shelter" app from Google Play, and it is blocked in the loading page. The notification did not show up at all, and the reason is that `DeviceAdminReceiver` did not receive the `onProfileProvisioningComplete` event. But it works well with [Google's sample project](https://github.com/googlearchive/android-BasicManagedProfile)...... So there must be a reason for it, not the compatibility problem because it works with Google's sample.

**Comment by mistereccos** [comment]
did you remove any apps via adb or root? especially huawei bloatware?

**Comment by PeterCxy** [comment]
Huawei devices are not supported, sorry.
