### ISSUE TITLE
Whatsapp is not sheltered

### ISSUE THREAD

**Issue by beeshyams** [PeterCxy/Shelter#9]
I cloned Whatsapp to shelter but could access gallery which is outside the shelter. Is it because Whatsapp is using some non standard ways of accessing?

In any case, I think it would be nice to have a log to see what has been requested by an app and whether it's accepted or denied. This would indirectly serve as proof that it works ( XprivacyLua does that in Pro version)

**Comment by PeterCxy** [comment]
I just tried installing WhatsApp in the Shelter. However, I didn't see it being able to view the gallery outside the profile: it is completely limited to the storage dedicated to the work profile.

Could it be that your ROM fails to implement such isolation?

**Comment by PeterCxy** [comment]
For now it is not possible to monitor the app's behavior due to the limitation of Device Admin API.

**Comment by PeterCxy** [comment]
My contact is completely empty by default in Shelter... Couldn't understand
why it wouldn't be the case on your device.

**Comment by PeterCxy** [comment]
Could you confirm that you are REALLY running the WhatsApp app INSIDE the
work profile? I confirmed again and again on my devices / emulators that
apps inside the work profile won't be able to read contacts and gallery
from main profile at all.

**Comment by beeshyams** [comment]
You are absolutely correct ! I don't know what went wrong the first time but I uninstalled Shelter, cloned Whatsapp to shelter and the contacts / gallery was empty. Kudos for excellent app . 

Thanks and am closing the issue
