### ISSUE TITLE
Cloned app crashes

### ISSUE THREAD

**Issue by monterrr** [PeterCxy/Shelter#91]
Installing Revolut app from APKPure and launching works on the main profile, the cloned version to the work profile crashes every time it's launched.

[logcat.txt](https://github.com/PeterCxy/Shelter/files/3832055/logcat.txt)

**Comment by drainboy** [comment]
do you have microg installed? some apps just don't work if they don't detect google services

**Comment by monterrr** [comment]
No, I don't in both profiles

**Comment by drainboy** [comment]
do you have magisk? if u have, try hiding the app in magisk

**Comment by monterrr** [comment]
Closing, the problem is not caused by this app.
