### ISSUE TITLE
How to transfer existing whatsapp data to shelter

### ISSUE THREAD

**Issue by ctranxuan** [PeterCxy/Shelter#99]
Hi,
I am trying to restore backups of whatsapp on a Whatsapp installed into shelter. But I don't know how to access to the install directory of Whatsapp within Shelter. I saw the there was a solution on the internet but the link is broken.

Thanks in advance for your answer!

**Comment by drainboy** [comment]
**remember to backup Whatsapp first before attempting**
1. copy the whole Whatsapp folder from your main profile into Shelter using a file manager in Shelter
2. clone Whatsapp into Shelter and launch it
after going through the login process, Whatsapp should automatically detect the database file and would prompt you

if you try to copy using a file manager in your main profile, the database file extension will change from .crypt12 to .null causing Whatsapp to not recognizing it

**Comment by ctranxuan** [comment]
It works fine! Just accept from WhatsApp to restore a a backup from Google Drive, then WhatsApp detect there is a local backup and offers to restore it.

Many thanks!
